#
# This file is part of LiteX-Boards.
#
# Copyright (c) 2021 Derek Mulcahy <derekmulcahy@gmail.com>
# Copyright (c) 2019-2020 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

from litex.build.generic_platform import *
from litex.build.xilinx import Xilinx7SeriesPlatform, VivadoProgrammer

# IOs ----------------------------------------------------------------------------------------------

_io = [
    # Clk / Rst - FIXME: A placeholder for an external clock
    ("clk100", 0, Pins("H16"), IOStandard("LVCMOS33")),

    # Leds - FIXME: A placeholder for an external LED
    ("user_led", 0, Pins("G14"), IOStandard("LVCMOS33")),

    # UART - FIXME: A placeholder for an external UART
    ("serial", 0,
        Subsignal("tx", Pins("D19")),
        Subsignal("rx", Pins("D20")),
        IOStandard("LVCMOS33"),
    ),

    # PS7
    ("ps7_clk",   0, Pins(1)),
    ("ps7_porb",  0, Pins(1)),
    ("ps7_srstb", 0, Pins(1)),
    ("ps7_mio",   0, Pins(54)),
    ("ps7_ddram", 0,
        Subsignal("addr",    Pins(15)),
        Subsignal("ba",      Pins(3)),
        Subsignal("cas_n",   Pins(1)),
        Subsignal("ck_n",    Pins(1)),
        Subsignal("ck_p",    Pins(1)),
        Subsignal("cke",     Pins(1)),
        Subsignal("cs_n",    Pins(1)),
        Subsignal("dm",      Pins(4)),
        Subsignal("dq",      Pins(32)),
        Subsignal("dqs_n",   Pins(4)),
        Subsignal("dqs_p",   Pins(4)),
        Subsignal("odt",     Pins(1)),
        Subsignal("ras_n",   Pins(1)),
        Subsignal("reset_n", Pins(1)),
        Subsignal("we_n",    Pins(1)),
        Subsignal("vrn",     Pins(1)),
        Subsignal("vrp",     Pins(1)),
    ),
]

# Connectors ---------------------------------------------------------------------------------------

#TODO: take ps7 params from snickerdoodle example vivado project
ps7_config_from_other_project = {
    'PCW_ACT_APU_PERIPHERAL_FREQMHZ':'866.665771',
    'PCW_ACT_CAN_PERIPHERAL_FREQMHZ':'10.000000',
    'PCW_ACT_DCI_PERIPHERAL_FREQMHZ':'10.062883',
    'PCW_ACT_ENET0_PERIPHERAL_FREQMHZ':'10.000000',
    'PCW_ACT_ENET1_PERIPHERAL_FREQMHZ':'10.000000',
    'PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ':'99.999893',
    'PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ':'10.000000',
    'PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ':'10.000000',
    'PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ':'10.000000',
    'PCW_ACT_PCAP_PERIPHERAL_FREQMHZ':'199.999786',
    'PCW_ACT_QSPI_PERIPHERAL_FREQMHZ':'199.999786',
    'PCW_ACT_SDIO_PERIPHERAL_FREQMHZ':'99.999893',
    'PCW_ACT_SMC_PERIPHERAL_FREQMHZ':'10.000000',
    'PCW_ACT_SPI_PERIPHERAL_FREQMHZ':'166.666489',
    'PCW_ACT_TPIU_PERIPHERAL_FREQMHZ':'200.000000',
    'PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ':'144.444305',
    'PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ':'144.444305',
    'PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ':'144.444305',
    'PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ':'144.444305',
    'PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ':'144.444305',
    'PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ':'144.444305',
    'PCW_ACT_UART_PERIPHERAL_FREQMHZ':'49.999947',
    'PCW_ACT_WDT_PERIPHERAL_FREQMHZ':'144.444305',
    'PCW_APU_CLK_RATIO_ENABLE':'6:2:1',
    'PCW_APU_PERIPHERAL_FREQMHZ':'867',
    'PCW_ARMPLL_CTRL_FBDIV':'52',
    'PCW_CAN_PERIPHERAL_DIVISOR0':'1',
    'PCW_CAN_PERIPHERAL_DIVISOR1':'1',
    'PCW_CLK0_FREQ':'99999893',
    'PCW_CLK1_FREQ':'10000000',
    'PCW_CLK2_FREQ':'10000000',
    'PCW_CLK3_FREQ':'10000000',
    'PCW_CPU_CPU_6X4X_MAX_RANGE':'867',
    'PCW_CPU_CPU_PLL_FREQMHZ':'1733.332',
    'PCW_CPU_PERIPHERAL_CLKSRC':'ARM PLL',
    'PCW_CPU_PERIPHERAL_DIVISOR0':'2',
    'PCW_CRYSTAL_PERIPHERAL_FREQMHZ':'33.3333',
    'PCW_DCI_PERIPHERAL_DIVISOR0':'53',
    'PCW_DCI_PERIPHERAL_DIVISOR1':'3',
    'PCW_DDRPLL_CTRL_FBDIV':'48',
    'PCW_DDR_DDR_PLL_FREQMHZ':'1599.998',
    'PCW_DDR_PERIPHERAL_CLKSRC':'DDR PLL',
    'PCW_DDR_PERIPHERAL_DIVISOR0':'4',
    'PCW_DDR_RAM_HIGHADDR':'0x3FFFFFFF',
    'PCW_DM_WIDTH':'4',
    'PCW_DQS_WIDTH':'4',
    'PCW_DQ_WIDTH':'32',
    'PCW_ENET0_PERIPHERAL_CLKSRC':'IO PLL',
    'PCW_ENET0_PERIPHERAL_DIVISOR0':'1',
    'PCW_ENET0_PERIPHERAL_DIVISOR1':'1',
    'PCW_ENET0_PERIPHERAL_FREQMHZ':'1000 Mbps',
    'PCW_ENET0_RESET_ENABLE':'0',
    'PCW_ENET1_PERIPHERAL_DIVISOR0':'1',
    'PCW_ENET1_PERIPHERAL_DIVISOR1':'1',
    'PCW_ENET1_RESET_ENABLE':'0',
    'PCW_ENET_RESET_ENABLE':'0',
    'PCW_EN_CLK0_PORT':'1',
    'PCW_EN_CLK1_PORT':'0',
    'PCW_EN_CLK2_PORT':'0',
    'PCW_EN_CLK3_PORT':'0',
    'PCW_EN_DDR':'1',
    'PCW_EN_EMIO_CD_SDIO1':'0',
    'PCW_EN_EMIO_GPIO':'1',
    'PCW_EN_EMIO_SDIO1':'0',
    'PCW_EN_EMIO_SPI1':'0',
    'PCW_EN_EMIO_UART0':'0',
    'PCW_EN_EMIO_WP_SDIO1':'0',
    'PCW_EN_GPIO':'1',
    'PCW_EN_QSPI':'1',
    'PCW_EN_RST0_PORT':'1',
    'PCW_EN_RST1_PORT':'0',
    'PCW_EN_RST2_PORT':'0',
    'PCW_EN_RST3_PORT':'0',
    'PCW_EN_SDIO0':'1',
    'PCW_EN_SDIO1':'1',
    'PCW_EN_SPI1':'1',
    'PCW_EN_UART0':'1',
    'PCW_FCLK0_PERIPHERAL_CLKSRC':'IO PLL',
    'PCW_FCLK0_PERIPHERAL_DIVISOR0':'5',
    'PCW_FCLK0_PERIPHERAL_DIVISOR1':'4',
    'PCW_FCLK1_PERIPHERAL_CLKSRC':'IO PLL',
    'PCW_FCLK1_PERIPHERAL_DIVISOR0':'1',
    'PCW_FCLK1_PERIPHERAL_DIVISOR1':'1',
    'PCW_FCLK2_PERIPHERAL_CLKSRC':'IO PLL',
    'PCW_FCLK2_PERIPHERAL_DIVISOR0':'1',
    'PCW_FCLK2_PERIPHERAL_DIVISOR1':'1',
    'PCW_FCLK3_PERIPHERAL_CLKSRC':'IO PLL',
    'PCW_FCLK3_PERIPHERAL_DIVISOR0':'1',
    'PCW_FCLK3_PERIPHERAL_DIVISOR1':'1',
    'PCW_FCLK_CLK0_BUF':'TRUE',
    'PCW_FCLK_CLK1_BUF':'FALSE',
    'PCW_FCLK_CLK2_BUF':'FALSE',
    'PCW_FCLK_CLK3_BUF':'FALSE',
    'PCW_FPGA0_PERIPHERAL_FREQMHZ':'100',
    'PCW_FPGA1_PERIPHERAL_FREQMHZ':'100',
    'PCW_FPGA2_PERIPHERAL_FREQMHZ':'150',
    'PCW_FPGA3_PERIPHERAL_FREQMHZ':'200',
    'PCW_FPGA_FCLK0_ENABLE':'1',
    'PCW_FPGA_FCLK1_ENABLE':'0',
    'PCW_FPGA_FCLK2_ENABLE':'0',
    'PCW_FPGA_FCLK3_ENABLE':'0',
    'PCW_GPIO_EMIO_GPIO_ENABLE':'1',
    'PCW_GPIO_EMIO_GPIO_IO':'64',
    'PCW_GPIO_EMIO_GPIO_WIDTH':'64',
    'PCW_GPIO_MIO_GPIO_ENABLE':'1',
    'PCW_GPIO_MIO_GPIO_IO':'MIO',
    'PCW_GPIO_PERIPHERAL_ENABLE':'1',
    'PCW_I2C0_RESET_ENABLE':'0',
    'PCW_I2C1_RESET_ENABLE':'0',
    'PCW_I2C_PERIPHERAL_FREQMHZ':'25',
    'PCW_I2C_RESET_ENABLE':'1',
    'PCW_IOPLL_CTRL_FBDIV':'60',
    'PCW_IO_IO_PLL_FREQMHZ':'1999.998',
    'PCW_IRQ_F2P_INTR':'1',
    'PCW_MIO_0_DIRECTION':'inout',
    'PCW_MIO_0_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_0_PULLUP':'disabled',
    'PCW_MIO_0_SLEW':'slow',
    'PCW_MIO_10_DIRECTION':'inout',
    'PCW_MIO_10_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_10_PULLUP':'enabled',
    'PCW_MIO_10_SLEW':'fast',
    'PCW_MIO_11_DIRECTION':'inout',
    'PCW_MIO_11_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_11_PULLUP':'enabled',
    'PCW_MIO_11_SLEW':'fast',
    'PCW_MIO_12_DIRECTION':'inout',
    'PCW_MIO_12_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_12_PULLUP':'enabled',
    'PCW_MIO_12_SLEW':'fast',
    'PCW_MIO_13_DIRECTION':'inout',
    'PCW_MIO_13_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_13_PULLUP':'enabled',
    'PCW_MIO_13_SLEW':'fast',
    'PCW_MIO_14_DIRECTION':'inout',
    'PCW_MIO_14_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_14_PULLUP':'enabled',
    'PCW_MIO_14_SLEW':'fast',
    'PCW_MIO_15_DIRECTION':'inout',
    'PCW_MIO_15_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_15_PULLUP':'enabled',
    'PCW_MIO_15_SLEW':'fast',
    'PCW_MIO_16_DIRECTION':'inout',
    'PCW_MIO_16_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_16_PULLUP':'disabled',
    'PCW_MIO_16_SLEW':'slow',
    'PCW_MIO_17_DIRECTION':'inout',
    'PCW_MIO_17_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_17_PULLUP':'disabled',
    'PCW_MIO_17_SLEW':'slow',
    'PCW_MIO_18_DIRECTION':'inout',
    'PCW_MIO_18_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_18_PULLUP':'disabled',
    'PCW_MIO_18_SLEW':'slow',
    'PCW_MIO_19_DIRECTION':'inout',
    'PCW_MIO_19_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_19_PULLUP':'disabled',
    'PCW_MIO_19_SLEW':'slow',
    'PCW_MIO_1_DIRECTION':'out',
    'PCW_MIO_1_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_1_PULLUP':'enabled',
    'PCW_MIO_1_SLEW':'fast',
    'PCW_MIO_20_DIRECTION':'inout',
    'PCW_MIO_20_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_20_PULLUP':'disabled',
    'PCW_MIO_20_SLEW':'slow',
    'PCW_MIO_21_DIRECTION':'inout',
    'PCW_MIO_21_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_21_PULLUP':'disabled',
    'PCW_MIO_21_SLEW':'slow',
    'PCW_MIO_22_DIRECTION':'inout',
    'PCW_MIO_22_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_22_PULLUP':'disabled',
    'PCW_MIO_22_SLEW':'slow',
    'PCW_MIO_23_DIRECTION':'inout',
    'PCW_MIO_23_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_23_PULLUP':'disabled',
    'PCW_MIO_23_SLEW':'slow',
    'PCW_MIO_24_DIRECTION':'inout',
    'PCW_MIO_24_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_24_PULLUP':'disabled',
    'PCW_MIO_24_SLEW':'slow',
    'PCW_MIO_25_DIRECTION':'inout',
    'PCW_MIO_25_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_25_PULLUP':'disabled',
    'PCW_MIO_25_SLEW':'slow',
    'PCW_MIO_26_DIRECTION':'inout',
    'PCW_MIO_26_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_26_PULLUP':'disabled',
    'PCW_MIO_26_SLEW':'slow',
    'PCW_MIO_27_DIRECTION':'inout',
    'PCW_MIO_27_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_27_PULLUP':'disabled',
    'PCW_MIO_27_SLEW':'slow',
    'PCW_MIO_28_DIRECTION':'inout',
    'PCW_MIO_28_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_28_PULLUP':'disabled',
    'PCW_MIO_28_SLEW':'slow',
    'PCW_MIO_29_DIRECTION':'inout',
    'PCW_MIO_29_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_29_PULLUP':'disabled',
    'PCW_MIO_29_SLEW':'slow',
    'PCW_MIO_2_DIRECTION':'inout',
    'PCW_MIO_2_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_2_PULLUP':'disabled',
    'PCW_MIO_2_SLEW':'fast',
    'PCW_MIO_30_DIRECTION':'inout',
    'PCW_MIO_30_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_30_PULLUP':'disabled',
    'PCW_MIO_30_SLEW':'slow',
    'PCW_MIO_31_DIRECTION':'inout',
    'PCW_MIO_31_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_31_PULLUP':'disabled',
    'PCW_MIO_31_SLEW':'slow',
    'PCW_MIO_32_DIRECTION':'inout',
    'PCW_MIO_32_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_32_PULLUP':'disabled',
    'PCW_MIO_32_SLEW':'slow',
    'PCW_MIO_33_DIRECTION':'inout',
    'PCW_MIO_33_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_33_PULLUP':'disabled',
    'PCW_MIO_33_SLEW':'slow',
    'PCW_MIO_34_DIRECTION':'inout',
    'PCW_MIO_34_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_34_PULLUP':'disabled',
    'PCW_MIO_34_SLEW':'slow',
    'PCW_MIO_35_DIRECTION':'inout',
    'PCW_MIO_35_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_35_PULLUP':'disabled',
    'PCW_MIO_35_SLEW':'slow',
    'PCW_MIO_36_DIRECTION':'inout',
    'PCW_MIO_36_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_36_PULLUP':'disabled',
    'PCW_MIO_36_SLEW':'slow',
    'PCW_MIO_37_DIRECTION':'inout',
    'PCW_MIO_37_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_37_PULLUP':'disabled',
    'PCW_MIO_37_SLEW':'slow',
    'PCW_MIO_38_DIRECTION':'inout',
    'PCW_MIO_38_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_38_PULLUP':'disabled',
    'PCW_MIO_38_SLEW':'slow',
    'PCW_MIO_39_DIRECTION':'inout',
    'PCW_MIO_39_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_39_PULLUP':'disabled',
    'PCW_MIO_39_SLEW':'slow',
    'PCW_MIO_3_DIRECTION':'inout',
    'PCW_MIO_3_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_3_PULLUP':'disabled',
    'PCW_MIO_3_SLEW':'fast',
    'PCW_MIO_40_DIRECTION':'inout',
    'PCW_MIO_40_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_40_PULLUP':'enabled',
    'PCW_MIO_40_SLEW':'fast',
    'PCW_MIO_41_DIRECTION':'inout',
    'PCW_MIO_41_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_41_PULLUP':'enabled',
    'PCW_MIO_41_SLEW':'fast',
    'PCW_MIO_42_DIRECTION':'inout',
    'PCW_MIO_42_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_42_PULLUP':'enabled',
    'PCW_MIO_42_SLEW':'fast',
    'PCW_MIO_43_DIRECTION':'inout',
    'PCW_MIO_43_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_43_PULLUP':'enabled',
    'PCW_MIO_43_SLEW':'fast',
    'PCW_MIO_44_DIRECTION':'inout',
    'PCW_MIO_44_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_44_PULLUP':'enabled',
    'PCW_MIO_44_SLEW':'fast',
    'PCW_MIO_45_DIRECTION':'inout',
    'PCW_MIO_45_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_45_PULLUP':'enabled',
    'PCW_MIO_45_SLEW':'fast',
    'PCW_MIO_46_DIRECTION':'inout',
    'PCW_MIO_46_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_46_PULLUP':'enabled',
    'PCW_MIO_46_SLEW':'slow',
    'PCW_MIO_47_DIRECTION':'inout',
    'PCW_MIO_47_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_47_PULLUP':'enabled',
    'PCW_MIO_47_SLEW':'slow',
    'PCW_MIO_48_DIRECTION':'inout',
    'PCW_MIO_48_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_48_PULLUP':'enabled',
    'PCW_MIO_48_SLEW':'slow',
    'PCW_MIO_49_DIRECTION':'inout',
    'PCW_MIO_49_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_49_PULLUP':'enabled',
    'PCW_MIO_49_SLEW':'slow',
    'PCW_MIO_4_DIRECTION':'inout',
    'PCW_MIO_4_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_4_PULLUP':'disabled',
    'PCW_MIO_4_SLEW':'fast',
    'PCW_MIO_50_DIRECTION':'in',
    'PCW_MIO_50_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_50_PULLUP':'enabled',
    'PCW_MIO_50_SLEW':'slow',
    'PCW_MIO_51_DIRECTION':'out',
    'PCW_MIO_51_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_51_PULLUP':'enabled',
    'PCW_MIO_51_SLEW':'slow',
    'PCW_MIO_52_DIRECTION':'inout',
    'PCW_MIO_52_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_52_PULLUP':'disabled',
    'PCW_MIO_52_SLEW':'slow',
    'PCW_MIO_53_DIRECTION':'inout',
    'PCW_MIO_53_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_53_PULLUP':'disabled',
    'PCW_MIO_53_SLEW':'slow',
    'PCW_MIO_5_DIRECTION':'inout',
    'PCW_MIO_5_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_5_PULLUP':'disabled',
    'PCW_MIO_5_SLEW':'fast',
    'PCW_MIO_6_DIRECTION':'out',
    'PCW_MIO_6_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_6_PULLUP':'disabled',
    'PCW_MIO_6_SLEW':'fast',
    'PCW_MIO_7_DIRECTION':'out',
    'PCW_MIO_7_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_7_PULLUP':'disabled',
    'PCW_MIO_7_SLEW':'slow',
    'PCW_MIO_8_DIRECTION':'out',
    'PCW_MIO_8_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_8_PULLUP':'disabled',
    'PCW_MIO_8_SLEW':'slow',
    'PCW_MIO_9_DIRECTION':'inout',
    'PCW_MIO_9_IOTYPE':'LVCMOS 1.8V',
    'PCW_MIO_9_PULLUP':'enabled',
    'PCW_MIO_9_SLEW':'slow',
    'PCW_MIO_PRIMITIVE':'54',
    'PCW_MIO_TREE_PERIPHERALS':'GPIO#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#GPIO#Quad SPI Flash#GPIO#SD 1#SD 1#SD 1#SD 1#SD 1#SD 1#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SPI 1#SPI 1#SPI 1#SPI 1#UART 0#UART 0#GPIO#GPIO',
    'PCW_MIO_TREE_SIGNALS':'gpio[0]#qspi0_ss_b#qspi0_io[0]#qspi0_io[1]#qspi0_io[2]#qspi0_io[3]/HOLD_B#qspi0_sclk#gpio[7]#qspi_fbclk#gpio[9]#data[0]#cmd#clk#data[1]#data[2]#data[3]#gpio[16]#gpio[17]#gpio[18]#gpio[19]#gpio[20]#gpio[21]#gpio[22]#gpio[23]#gpio[24]#gpio[25]#gpio[26]#gpio[27]#gpio[28]#gpio[29]#gpio[30]#gpio[31]#gpio[32]#gpio[33]#gpio[34]#gpio[35]#gpio[36]#gpio[37]#gpio[38]#gpio[39]#clk#cmd#data[0]#data[1]#data[2]#data[3]#mosi#miso#sclk#ss[0]#rx#tx#gpio[52]#gpio[53]',
    'PCW_NAND_GRP_D8_ENABLE':'0',
    'PCW_NAND_PERIPHERAL_ENABLE':'0',
    'PCW_NOR_GRP_A25_ENABLE':'0',
    'PCW_NOR_GRP_CS0_ENABLE':'0',
    'PCW_NOR_GRP_CS1_ENABLE':'0',
    'PCW_NOR_GRP_SRAM_CS0_ENABLE':'0',
    'PCW_NOR_GRP_SRAM_CS1_ENABLE':'0',
    'PCW_NOR_GRP_SRAM_INT_ENABLE':'0',
    'PCW_NOR_PERIPHERAL_ENABLE':'0',
    'PCW_PACKAGE_NAME':'clg400',
    'PCW_PCAP_PERIPHERAL_DIVISOR0':'10',
    'PCW_PRESET_BANK0_VOLTAGE':'LVCMOS 1.8V',
    'PCW_PRESET_BANK1_VOLTAGE':'LVCMOS 1.8V',
    'PCW_QSPI_GRP_FBCLK_ENABLE':'1',
    'PCW_QSPI_GRP_FBCLK_IO':'MIO 8',
    'PCW_QSPI_GRP_IO1_ENABLE':'0',
    'PCW_QSPI_GRP_SINGLE_SS_ENABLE':'1',
    'PCW_QSPI_GRP_SINGLE_SS_IO':'MIO 1 .. 6',
    'PCW_QSPI_GRP_SS1_ENABLE':'0',
    'PCW_QSPI_PERIPHERAL_CLKSRC':'IO PLL',
    'PCW_QSPI_PERIPHERAL_DIVISOR0':'10',
    'PCW_QSPI_PERIPHERAL_ENABLE':'1',
    'PCW_QSPI_PERIPHERAL_FREQMHZ':'200.000000',
    'PCW_QSPI_QSPI_IO':'MIO 1 .. 6',
    'PCW_SD0_GRP_CD_ENABLE':'0',
    'PCW_SD0_GRP_POW_ENABLE':'0',
    'PCW_SD0_GRP_WP_ENABLE':'0',
    'PCW_SD0_PERIPHERAL_ENABLE':'1',
    'PCW_SD0_SD0_IO':'MIO 40 .. 45',
    'PCW_SD1_GRP_CD_ENABLE':'0',
    'PCW_SD1_GRP_POW_ENABLE':'0',
    'PCW_SD1_GRP_WP_ENABLE':'0',
    'PCW_SD1_PERIPHERAL_ENABLE':'1',
    'PCW_SD1_SD1_IO':'MIO 10 .. 15',
    'PCW_SDIO_PERIPHERAL_CLKSRC':'IO PLL',
    'PCW_SDIO_PERIPHERAL_DIVISOR0':'20',
    'PCW_SDIO_PERIPHERAL_FREQMHZ':'100',
    'PCW_SDIO_PERIPHERAL_VALID':'1',
    'PCW_SINGLE_QSPI_DATA_MODE':'x4',
    'PCW_SMC_PERIPHERAL_DIVISOR0':'1',
    'PCW_SPI1_GRP_SS0_ENABLE':'1',
    'PCW_SPI1_GRP_SS0_IO':'MIO 49',
    'PCW_SPI1_GRP_SS1_ENABLE':'0',
    'PCW_SPI1_GRP_SS2_ENABLE':'0',
    'PCW_SPI1_PERIPHERAL_ENABLE':'1',
    'PCW_SPI1_SPI1_IO':'MIO 46 .. 51',
    'PCW_SPI_PERIPHERAL_DIVISOR0':'12',
    'PCW_SPI_PERIPHERAL_FREQMHZ':'166.666666',
    'PCW_SPI_PERIPHERAL_VALID':'1',
    'PCW_TPIU_PERIPHERAL_DIVISOR0':'1',
    'PCW_TTC0_CLK0_PERIPHERAL_CLKSRC':'CPU_1X',
    'PCW_TTC0_CLK0_PERIPHERAL_FREQMHZ':'133.333333',
    'PCW_TTC0_CLK1_PERIPHERAL_CLKSRC':'CPU_1X',
    'PCW_TTC0_CLK1_PERIPHERAL_FREQMHZ':'133.333333',
    'PCW_TTC0_CLK2_PERIPHERAL_CLKSRC':'CPU_1X',
    'PCW_TTC0_CLK2_PERIPHERAL_FREQMHZ':'133.333333',
    'PCW_UART0_GRP_FULL_ENABLE':'0',
    'PCW_UART0_PERIPHERAL_ENABLE':'1',
    'PCW_UART0_UART0_IO':'MIO 50 .. 51',
    'PCW_UART_PERIPHERAL_CLKSRC':'IO PLL',
    'PCW_UART_PERIPHERAL_DIVISOR0':'40',
    'PCW_UART_PERIPHERAL_FREQMHZ':'50',
    'PCW_UART_PERIPHERAL_VALID':'1',
    'PCW_UIPARAM_ACT_DDR_FREQ_MHZ':'399.999603',
    'PCW_UIPARAM_DDR_BANK_ADDR_COUNT':'3',
    'PCW_UIPARAM_DDR_BL':'8',
    'PCW_UIPARAM_DDR_BOARD_DELAY0':'0.436',
    'PCW_UIPARAM_DDR_BOARD_DELAY1':'0.436',
    'PCW_UIPARAM_DDR_BOARD_DELAY2':'0.436',
    'PCW_UIPARAM_DDR_BOARD_DELAY3':'0.436',
    'PCW_UIPARAM_DDR_BUS_WIDTH':'32 Bit',
    'PCW_UIPARAM_DDR_CL':'6',
    'PCW_UIPARAM_DDR_COL_ADDR_COUNT':'11',
    'PCW_UIPARAM_DDR_CWL':'NA',
    'PCW_UIPARAM_DDR_DEVICE_CAPACITY':'8192 MBits',
    'PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0':'0.004',
    'PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1':'0.004',
    'PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2':'0.004',
    'PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3':'0.004',
    'PCW_UIPARAM_DDR_DRAM_WIDTH':'32 Bits',
    'PCW_UIPARAM_DDR_ECC':'Disabled',
    'PCW_UIPARAM_DDR_FREQ_MHZ':'400',
    'PCW_UIPARAM_DDR_MEMORY_TYPE':'LPDDR 2',
    'PCW_UIPARAM_DDR_PARTNO':'Custom',
    'PCW_UIPARAM_DDR_ROW_ADDR_COUNT':'14',
    'PCW_UIPARAM_DDR_SPEED_BIN':'LPDDR2_1066',
    'PCW_UIPARAM_DDR_TRAIN_DATA_EYE':'1',
    'PCW_UIPARAM_DDR_TRAIN_READ_GATE':'1',
    'PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL':'0',
    'PCW_UIPARAM_DDR_T_FAW':'50.0',
    'PCW_UIPARAM_DDR_T_RAS_MIN':'42.0',
    'PCW_UIPARAM_DDR_T_RC':'63.0',
    'PCW_UIPARAM_DDR_T_RCD':'8',
    'PCW_UIPARAM_DDR_T_RP':'9',
    'PCW_UIPARAM_DDR_USE_INTERNAL_VREF':'0',
    'PCW_USB0_PERIPHERAL_FREQMHZ':'60',
    'PCW_USB0_RESET_ENABLE':'0',
    'PCW_USB1_RESET_ENABLE':'0',
    'PCW_USB_RESET_ENABLE':'1',
    'PCW_USE_FABRIC_INTERRUPT':'1',
    'PCW_USE_M_AXI_GP0':'1',
    'PCW_USE_M_AXI_GP1':'0',
    'PCW_USE_S_AXI_ACP':'0',
}

# this is from the arty board i believe, but i am just seeing if reverting to this allows synthesis in
# vivado to complete...
ps7_config = {
    "PCW_PRESET_BANK1_VOLTAGE"           : "LVCMOS 1.8V",
    "PCW_CRYSTAL_PERIPHERAL_FREQMHZ"     : "50",
    "PCW_APU_PERIPHERAL_FREQMHZ"         : "650",
    "PCW_SDIO_PERIPHERAL_FREQMHZ"        : "50",
    "PCW_FPGA0_PERIPHERAL_FREQMHZ"       : "100",
    "PCW_UIPARAM_DDR_FREQ_MHZ"           : "525",
    "PCW_UIPARAM_DDR_BUS_WIDTH"          : "16 Bit",
    "PCW_UIPARAM_DDR_PARTNO"             : "MT41J256M16 RE-125",
    "PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0" : "0.040",
    "PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1" : "0.058",
    "PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2" : "-0.009",
    "PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3" : "-0.033",
    "PCW_UIPARAM_DDR_BOARD_DELAY0"       : "0.223",
    "PCW_UIPARAM_DDR_BOARD_DELAY1"       : "0.212",
    "PCW_UIPARAM_DDR_BOARD_DELAY2"       : "0.085",
    "PCW_UIPARAM_DDR_BOARD_DELAY3"       : "0.092",
    "PCW_QSPI_PERIPHERAL_ENABLE"         : "1",
    "PCW_QSPI_GRP_SINGLE_SS_ENABLE"      : "1",
    "PCW_QSPI_GRP_FBCLK_ENABLE"          : "1",
    "PCW_ENET0_PERIPHERAL_ENABLE"        : "1",
    "PCW_ENET0_ENET0_IO"                 : "MIO 16 .. 27",
    "PCW_ENET0_GRP_MDIO_ENABLE"          : "1",
    "PCW_ENET0_GRP_MDIO_IO"              : "MIO 52 .. 53",
    "PCW_ENET0_RESET_ENABLE"             : "1",
    "PCW_ENET0_RESET_IO"                 : "MIO 9",
    "PCW_SD0_PERIPHERAL_ENABLE"          : "1",
    "PCW_SD0_GRP_CD_ENABLE"              : "1",
    "PCW_SD0_GRP_CD_IO"                  : "MIO 47",
    "PCW_UART0_PERIPHERAL_ENABLE"        : "1",
    "PCW_UART0_UART0_IO"                 : "MIO 14 .. 15",
    "PCW_USB0_PERIPHERAL_ENABLE"         : "1",
    "PCW_USB0_RESET_ENABLE"              : "1",
    "PCW_USB0_RESET_IO"                  : "MIO 46",
    "PCW_GPIO_MIO_GPIO_ENABLE"           : "1",
    "PCW_GPIO_MIO_GPIO_IO"               : "MIO",
    "PCW_GPIO_EMIO_GPIO_ENABLE"          : "0",
}

_connectors = [
    ("ja1", "- - - G14 E18 D20 E19 D19 - - F16 B20 F17 C20 - - E17 A20 D18 B19 - - F19 G20 F20 G19 - - J20 G18 H20 G17 - - J18 H17 H18 H16 - -"),
    ("ja2", "- - - J15 L14 J16 L15 K16 - - M14 G15 M15 H15 - - N15 J14 N16 K14 - - L19 J19 L20 K19 - - M17 M20 M18 M19 - - L16 K18 L17 K17 - -"),
    ("jb1", "- - - T19 T11 U12 T10 T12 - - P14 W13 R14 V12 - - U13 T14 V13 T14 - - T16 Y17 U17 Y16 - - W14 W15 Y14 V15 - - U14 U19 U15 U18 - -"),
    ("jb2", "- - - R19 N17 P16 P18 P15 - - T17 R17 R18 R16 - - V17 W19 V18 W18 - - T20 W16 U20 V16 - - V20 Y19 W20 Y18 - - N20 P19 P20 N18 - -"),
    ("jc1", "- - - V5  U7  U10 V7  T9  - - T5  Y13 U5  Y12 - - V11 W6  V10 V6  - - V8  Y11 W8  W11 - - U9  W9  U8  W10 - - Y9  Y6  Y8  Y7  - -"),
    # ("xadc", "N15 L14 K16 K14 N16 L15 J16 J14"),
    # ("mrcc", "H17 H16 K18 K17 U19 U18 P19 N18 Y6 Y7"),
    # ("srcc", "J18 H18 L16 L17 U14 U15 N20 P20 Y9 Y8"),
]

# Platform -----------------------------------------------------------------------------------------

class Platform(Xilinx7SeriesPlatform):
    # The clock speed depends on the PS7 PLL configuration for the FCLK_CLK0 signal.
    default_clk_name   = "clk100"
    default_clk_freq   = 100e6

    def __init__(self, variant="z7-10", toolchain="vivado"):
        if toolchain == 'vivado':
            device = {
                "z7-10": "xc7z010-clg400-1",
                "z7-20": "xc7z020-clg400-3"
            }[variant]
        elif toolchain in ('openxc7', 'yosys+nextpnr'):
            device = {
                "z7-10": "xc7z010clg400-1",
                "z7-20": "xc7z020clg400-3"
            }[variant]
        else:
            raise RuntimeError(f'unsupported toolchain: {toolchain}')

        Xilinx7SeriesPlatform.__init__(self, device, _io,  _connectors, toolchain=toolchain)
        self.ps7_config = ps7_config
        self.default_clk_period = 1e9 / self.default_clk_freq
        self.toolchain.bitstream_commands = [
            "set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]"
        ]

    def create_programmer(self):
        return VivadoProgrammer(flash_part="n25q128a")

    def do_finalize(self, fragment):
        Xilinx7SeriesPlatform.do_finalize(self, fragment)
        self.add_period_constraint(self.lookup_request(self.default_clk_name, loose=True), self.default_clk_period)
